# Generated by Django 4.2.26 on 2025-11-18 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('DeptName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True)),
                ('device_name', models.CharField(blank=True, max_length=128, null=True)),
                ('device_type', models.IntegerField(default=0)),
                ('comm_type', models.CharField(blank=True, max_length=32, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('fw_version', models.CharField(blank=True, max_length=64, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.area')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('badgenumber', models.CharField(blank=True, max_length=32, null=True)),
                ('firstname', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('card_number', models.CharField(blank=True, max_length=64, null=True)),
                ('site_code', models.CharField(blank=True, max_length=32, null=True)),
                ('pager', models.CharField(blank=True, max_length=32, null=True)),
                ('hiredday', models.DateField(blank=True, null=True)),
                ('defaultdept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.dept')),
            ],
        ),
        migrations.CreateModel(
            name='IssueCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=64)),
                ('cardstatus', models.CharField(blank=True, max_length=32, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legacy_models.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.device')),
            ],
        ),
    ]
