# Generated by Django 4.2.26 on 2025-11-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_models', '0002_device_acpanel_type_device_com_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cardno', models.CharField(blank=True, max_length=64, null=True)),
                ('event_type', models.CharField(blank=True, max_length=64, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.device')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.door')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_models.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
