# Generated by Django 4.2.26 on 2025-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_models', '0005_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.RemoveField(
            model_name='issuecard',
            name='userid',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='IssueCard',
        ),
    ]
