# Generated by Django 4.2.26 on 2025-11-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRealtimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('sn', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'created_at'], name='agent_devic_device__27955d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('sn', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp_str', models.CharField(blank=True, default='', max_length=32)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('raw_line', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'created_at'], name='agent_devic_device__2ea83b_idx'), models.Index(fields=['code'], name='agent_devic_code_f19d65_idx')],
            },
        ),
    ]
