# Generated by Django 4.2.26 on 2025-11-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True)),
                ('door_state', models.CharField(default='CLOSED', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='agent_devic_serial__b239a3_idx',
            old_name='agent_devic_serial__idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='agent_devic_ip_addr_362efa_idx',
            old_name='agent_devic_ip_addre_idx',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.device'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['device', 'updated_at'], name='agent_devic_device__efb73e_idx'),
        ),
    ]
