# Generated by Django 4.2.26 on 2025-11-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_devicestatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("days_mask", models.PositiveSmallIntegerField(default=127)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="agent_times_name_edd415_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("date", models.DateField(unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="agent_holid_date_76f04c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Door",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, default="", max_length=128)),
                ("normally_open", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("is_open", models.BooleanField(default=False)),
                ("last_state_change", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("doors", models.ManyToManyField(blank=True, to="agent.door")),
                (
                    "time_segments",
                    models.ManyToManyField(blank=True, to="agent.timesegment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("card_number", models.CharField(max_length=32, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_levels",
                    models.ManyToManyField(blank=True, to="agent.accesslevel"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["card_number"], name="agent_emplo_card_nu_53dbf2_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="door",
            index=models.Index(fields=["name"], name="agent_door_name_cb2a03_idx"),
        ),
        migrations.AddIndex(
            model_name="accesslevel",
            index=models.Index(fields=["name"], name="agent_acces_name_55d941_idx"),
        ),
    ]
