# Generated by Django 4.2.26 on 2025-11-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_timesegment_holiday_door_accesslevel_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("result", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent.device",
                    ),
                ),
                (
                    "door",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent.door",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="agent_comma_created_a71f56_idx"
                    ),
                    models.Index(
                        fields=["status"], name="agent_comma_status_133983_idx"
                    ),
                ],
            },
        ),
    ]
