# Generated by Django 4.2.26 on 2025-11-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_commandlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAccessCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agent.door"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agent.employee"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "door"],
                        name="agent_emplo_employe_120f82_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="agent_emplo_updated_ef76b2_idx"
                    ),
                ],
                "unique_together": {("employee", "door")},
            },
        ),
    ]
