# Generated by Django 4.2.26 on 2025-11-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_employeeaccesscache"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="agent.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["card_number"], name="agent_employ_card_9461b4_idx"),
                    models.Index(fields=["employee"], name="agent_employ_employee_78a0f9_idx"),
                ],
            },
        ),
    ]
