# Generated by Django 4.2.26 on 2025-11-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_employeecard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeecard',
            new_name='agent_emplo_card_nu_de4834_idx',
            old_name='agent_employ_card_9461b4_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecard',
            new_name='agent_emplo_employe_5e15e8_idx',
            old_name='agent_employ_employee_78a0f9_idx',
        ),
    ]
