# Generated by Django 4.2.26 on 2025-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_rename_agent_employ_card_9461b4_idx_agent_emplo_card_nu_de4834_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Access Control Device', 'verbose_name_plural': 'Access Control Devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='auto_sync_time',
            field=models.BooleanField(default=True, help_text='Automatically sync time to device'),
        ),
        migrations.AddField(
            model_name='device',
            name='clear_on_add',
            field=models.BooleanField(default=False, help_text='Clear device data when adding to system'),
        ),
        migrations.AddField(
            model_name='device',
            name='comm_mode',
            field=models.CharField(choices=[('tcp', 'TCP/IP'), ('rs485', 'RS485')], default='tcp', help_text='TCP/IP or RS485', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='comm_password',
            field=models.CharField(blank=True, default='', help_text='Device communication password', max_length=128),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_version',
            field=models.CharField(blank=True, default='', help_text='Hardware version', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='last_contact',
            field=models.DateTimeField(blank=True, help_text='Last successful communication', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=4370, help_text='Communication port (default 4370 for ZK)'),
        ),
        migrations.AddField(
            model_name='device',
            name='rs485_address',
            field=models.IntegerField(blank=True, help_text='Device address on RS485 bus', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='rs485_baudrate',
            field=models.IntegerField(default=9600, help_text='Baud rate for RS485'),
        ),
        migrations.AddField(
            model_name='device',
            name='rs485_port',
            field=models.CharField(blank=True, default='COM1', help_text='Serial port for RS485 (e.g., COM1, /dev/ttyUSB0)', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='time_zone',
            field=models.CharField(blank=True, default='', help_text='Device time zone', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='area_name',
            field=models.CharField(blank=True, default='', help_text='Physical area/location', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('access_panel', 'Access Control Panel'), ('door_controller', 'Door Controller'), ('biometric_reader', 'Biometric Reader'), ('two_door_panel', 'Two-Door Access Control Panel'), ('multi_door_panel', 'Multi-Door Access Control Panel')], default='access_panel', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is device enabled for polling'),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, default='', help_text='Firmware version', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for TCP/IP devices', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Device display name (e.g., FINANCIAR, MEDICAL)', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Device serial number for identification', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['enabled'], name='agent_devic_enabled_6456f9_idx'),
        ),
    ]
