# Generated by Django 5.2.8 on 2025-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_add_device_comm_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='acc_enddate',
            field=models.DateField(blank=True, help_text='Data sfârșit valabilitate acces', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='acc_startdate',
            field=models.DateField(blank=True, help_text='Data început valabilitate acces', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='access_superuser',
            field=models.BooleanField(default=False, help_text='Superuser acces'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, help_text='Data nașterii', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='card_type',
            field=models.CharField(blank=True, default='', help_text='Tip card (WITH/WITHOUT Site Code)', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Oraș', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='delayed_door_open',
            field=models.BooleanField(default=False, help_text='Are întârziere la deschiderea ușii'),
        ),
        migrations.AddField(
            model_name='employee',
            name='elevator_level',
            field=models.CharField(blank=True, default='', help_text='Nivel / grup lift', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='elevator_superuser',
            field=models.BooleanField(default=False, help_text='Acces special lift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email contact', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='emptype',
            field=models.CharField(blank=True, default='', help_text='Tip personal', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='extend_time',
            field=models.IntegerField(blank=True, help_text='Extensie timp suplimentar (1-254)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, default='', help_text='Gen (M/F)', max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Data angajării în companie', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hiretype',
            field=models.CharField(blank=True, default='', help_text='Tip angajare', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_phone',
            field=models.CharField(blank=True, default='', help_text='Telefon acasă', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='homeaddress',
            field=models.CharField(blank=True, default='', help_text='Adresă domiciliu', max_length=256),
        ),
        migrations.AddField(
            model_name='employee',
            name='identitycard',
            field=models.CharField(blank=True, default='', help_text='Adresă de lucru', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='legacy_userid',
            field=models.IntegerField(blank=True, help_text='Identificator numeric unic din sistemul vechi', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', help_text='Telefon mobil', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='multi_card_group',
            field=models.CharField(blank=True, default='', help_text='Grup multi-card', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_on_record',
            field=models.CharField(blank=True, default='', help_text='Parolă 6 cifre', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Telefon birou', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='privilege',
            field=models.CharField(blank=True, default='', help_text='Nivel de privilegiu/rol', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='reservation_password',
            field=models.CharField(blank=True, default='123456', help_text='Parolă rezervare / acces secundar', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_on_device',
            field=models.CharField(blank=True, default='', help_text='Rol pe dispozitiv', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='selfpassword',
            field=models.CharField(blank=True, default='', help_text='Parolă autogestiune (opțional)', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='set_validity',
            field=models.BooleanField(default=False, help_text='Setează validitate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='site_code',
            field=models.CharField(blank=True, default='', help_text='Cod / prefix card (site)', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, default='', help_text='Social Security Number', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Stradă / detaliu adresă', max_length=256),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['legacy_userid'], name='agent_emplo_legacy__b45c9f_idx'),
        ),
    ]
