# Generated by Django 5.2.8 on 2025-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_employee_acc_enddate_employee_acc_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='secondary_card_number',
            field=models.CharField(blank=True, help_text='Card secundar', max_length=32, null=True, unique=True),
        ),
    ]
