# Generated by Django 5.2.8 on 2025-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_employee_secondary_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_id',
            field=models.IntegerField(blank=True, help_text='ID Departament (referință la legacy Dept)', null=True),
        ),
    ]
