# Generated by Django 4.2.26 on 2025-12-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_employee_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(blank=True, max_length=128, null=True)),
                ('module', models.CharField(db_index=True, max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('entity_name', models.CharField(blank=True, max_length=256, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'entity_id', '-timestamp'], name='agent_audit_module_c0e42a_idx')],
            },
        ),
    ]
