# Generated by Django 4.2.26 on 2025-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scanner_linked',
            field=models.BooleanField(default=False, help_text='Device is used by card scanners'),
        ),
        migrations.AddField(
            model_name='device',
            name='scanner_type',
            field=models.CharField(blank=True, default='', help_text='Scanner type: acp/elatec', max_length=16),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['scanner_linked'], name='agent_devic_scanner_2a3c90_idx'),
        ),
    ]
