# Generated by Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0014_device_scanner_linked_device_scanner_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSTime",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("start_month", models.PositiveSmallIntegerField()),
                ("start_week", models.CharField(choices=[("first", "First"), ("second", "Second"), ("third", "Third"), ("fourth", "Fourth"), ("last", "Last")], default="last", max_length=8)),
                ("start_weekday", models.PositiveSmallIntegerField(default=0)),
                ("start_hour", models.PositiveSmallIntegerField(default=3)),
                ("start_minute", models.PositiveSmallIntegerField(default=0)),
                ("end_month", models.PositiveSmallIntegerField()),
                ("end_week", models.CharField(choices=[("first", "First"), ("second", "Second"), ("third", "Third"), ("fourth", "Fourth"), ("last", "Last")], default="last", max_length=8)),
                ("end_weekday", models.PositiveSmallIntegerField(default=0)),
                ("end_hour", models.PositiveSmallIntegerField(default=3)),
                ("end_minute", models.PositiveSmallIntegerField(default=0)),
                ("offset_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="agent_dstime_name_92f669_idx"),
                    models.Index(fields=["start_month", "end_month"], name="agent_dstime_start_m_1f5b78_idx"),
                ],
            },
        ),
    ]
