# Generated by Django 4.2.26 on 2026-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_dstime'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dstime',
            new_name='agent_dstim_name_b55232_idx',
            old_name='agent_dstime_name_92f669_idx',
        ),
        migrations.RenameIndex(
            model_name='dstime',
            new_name='agent_dstim_start_m_25aae4_idx',
            old_name='agent_dstime_start_m_1f5b78_idx',
        ),
        migrations.AlterField(
            model_name='dstime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
