# Generated by Django 4.2.26 on 2026-01-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_legacyareameta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legacyareameta',
            new_name='agent_legac_legacy__13dc4c_idx',
            old_name='agent_legacya_legacy__d658d2_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyareameta',
            new_name='agent_legac_code_b28787_idx',
            old_name='agent_legacya_code_5b5452_idx',
        ),
    ]
