# Generated by Copilot on 2026-01-14

from django.db import migrations, models


def backfill_cards(apps, schema_editor):
    Employee = apps.get_model('agent', 'Employee')
    EmployeeCard = apps.get_model('agent', 'EmployeeCard')

    # Ensure existing additional cards have a slot/status.
    EmployeeCard.objects.filter(slot__isnull=True).update(slot='additional')
    EmployeeCard.objects.filter(status__isnull=True).update(status='Active')

    # Backfill primary/secondary employee cards into EmployeeCard so the UI has numeric IDs.
    for emp in Employee.objects.all():
        primary = (getattr(emp, 'card_number', None) or '').strip()
        secondary = (getattr(emp, 'secondary_card_number', None) or '').strip()

        if primary:
            try:
                existing = EmployeeCard.objects.filter(card_number__iexact=primary).first()
                if existing:
                    if existing.employee_id == emp.id and existing.slot != 'primary':
                        existing.slot = 'primary'
                        existing.save(update_fields=['slot'])
                else:
                    EmployeeCard.objects.create(employee_id=emp.id, card_number=primary, slot='primary', status='Active')
            except Exception:
                pass

        if secondary:
            try:
                existing = EmployeeCard.objects.filter(card_number__iexact=secondary).first()
                if existing:
                    if existing.employee_id == emp.id and existing.slot != 'secondary':
                        existing.slot = 'secondary'
                        existing.save(update_fields=['slot'])
                else:
                    EmployeeCard.objects.create(employee_id=emp.id, card_number=secondary, slot='secondary', status='Active')
            except Exception:
                pass


def reverse_backfill_cards(apps, schema_editor):
    # Non-destructive reverse; keep rows.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_rename_agent_legacya_legacy__d658d2_idx_agent_legac_legacy__13dc4c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='slot',
            field=models.CharField(
                db_index=True,
                default='additional',
                help_text='Slot card: primary/secondary/additional',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='status',
            field=models.CharField(
                db_index=True,
                default='Active',
                help_text='Stare card: Active/Inactive/Suspended',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='site_code',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Site code / prefix',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Data expirare', null=True),
        ),
        migrations.RunPython(backfill_cards, reverse_backfill_cards),
    ]
