# Generated by Django 4.2.26 on 2026-01-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_employeecard_fields_and_backfill'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeecard',
            index=models.Index(fields=['slot'], name='agent_emplo_slot_afcac6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecard',
            index=models.Index(fields=['status'], name='agent_emplo_status_17c14a_idx'),
        ),
    ]
