# Generated by Django 4.2.26 on 2026-01-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_door_door_number_and_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorFirstCardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorMultiCardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('required_count', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='door',
            new_name='agent_door_device__39047e_idx',
            old_name='agent_door_device__c34d09_idx',
        ),
        migrations.AddField(
            model_name='door',
            name='close_and_reverse_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='door',
            name='door_active_time_zone',
            field=models.ForeignKey(blank=True, help_text='Door Active Time Zone (legacy Door Details)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors_active_tz', to='agent.timesegment'),
        ),
        migrations.AddField(
            model_name='door',
            name='door_passage_mode_time_zone',
            field=models.ForeignKey(blank=True, help_text='Door Passage Mode Time Zone (legacy Door Details)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors_passage_tz', to='agent.timesegment'),
        ),
        migrations.AddField(
            model_name='door',
            name='door_sensor_type',
            field=models.CharField(choices=[('none', 'None'), ('normal_close', 'Normal Close'), ('normal_open', 'Normal Open')], default='normal_close', max_length=20),
        ),
        migrations.AddField(
            model_name='door',
            name='door_status_delay',
            field=models.PositiveSmallIntegerField(default=15, help_text='Door Status Delay (1-254 seconds)'),
        ),
        migrations.AddField(
            model_name='door',
            name='duress_password',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='door',
            name='emergency_password',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='door',
            name='lock_open_duration',
            field=models.PositiveSmallIntegerField(default=5, help_text='Lock Open Duration (0-254 seconds)'),
        ),
        migrations.AddField(
            model_name='door',
            name='punch_interval',
            field=models.PositiveSmallIntegerField(default=2, help_text='Punch Interval (0-254 seconds)'),
        ),
        migrations.AddField(
            model_name='door',
            name='verify_mode',
            field=models.CharField(choices=[('only_card', 'Only Card'), ('card_pin', 'Card + PIN'), ('card_fingerprint', 'Card + Fingerprint'), ('fingerprint', 'Fingerprint'), ('face', 'Face'), ('multi', 'Multi-Verify')], default='only_card', max_length=32),
        ),
        migrations.AddField(
            model_name='doormulticardrule',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_card_rules', to='agent.door'),
        ),
        migrations.AddField(
            model_name='doormulticardrule',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='multi_card_rules', to='agent.employee'),
        ),
        migrations.AddField(
            model_name='doorfirstcardrule',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_card_rules', to='agent.door'),
        ),
        migrations.AddField(
            model_name='doorfirstcardrule',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='first_card_rules', to='agent.employee'),
        ),
        migrations.AddField(
            model_name='doorfirstcardrule',
            name='time_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_card_rules', to='agent.timesegment'),
        ),
        migrations.AddIndex(
            model_name='doormulticardrule',
            index=models.Index(fields=['door', 'created_at'], name='agent_doorm_door_id_888235_idx'),
        ),
        migrations.AddIndex(
            model_name='doorfirstcardrule',
            index=models.Index(fields=['door', 'created_at'], name='agent_doorf_door_id_583fb5_idx'),
        ),
    ]
