# Generated by Django 4.2.26 on 2026-02-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_device_network_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32')], help_text='Door index on controller (1-32)', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='door_sensor_type',
            field=models.CharField(choices=[('none', 'Niciunul'), ('normal_close', 'Normal închis'), ('normal_open', 'Normal deschis')], default='normal_close', max_length=20),
        ),
        migrations.AlterField(
            model_name='door',
            name='verify_mode',
            field=models.CharField(choices=[('only_card', 'Doar card'), ('card_pin', 'Card + PIN'), ('card_fingerprint', 'Card + Amprentă'), ('fingerprint', 'Amprentă'), ('face', 'Față'), ('multi', 'Multi-verificare')], default='only_card', max_length=32),
        ),
        migrations.AlterField(
            model_name='timezonesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
