# Generated by Django 4.2.26 on 2026-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0034_accesslevel_visitor_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiegandCardFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiegand_name', models.CharField(max_length=64, unique=True)),
                ('default_fmt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('system_defined', models.BooleanField(default=False)),
                ('wiegand_count', models.PositiveSmallIntegerField(default=26)),
                ('wiegand_mode', models.PositiveSmallIntegerField(choices=[(1, 'Mode 1'), (2, 'Mode 2')], default=1)),
                ('first_p', models.PositiveSmallIntegerField(default=0)),
                ('second_p', models.PositiveSmallIntegerField(default=0)),
                ('even_parity_start', models.PositiveSmallIntegerField(default=0)),
                ('even_parity_count', models.PositiveSmallIntegerField(default=0)),
                ('odd_parity_start', models.PositiveSmallIntegerField(default=0)),
                ('odd_parity_count', models.PositiveSmallIntegerField(default=0)),
                ('cid_start', models.PositiveSmallIntegerField(default=0)),
                ('cid_count', models.PositiveSmallIntegerField(default=0)),
                ('facility_code_start', models.PositiveSmallIntegerField(default=0)),
                ('facility_code_count', models.PositiveSmallIntegerField(default=0)),
                ('site_code_start', models.PositiveSmallIntegerField(default=0)),
                ('site_code_count', models.PositiveSmallIntegerField(default=0)),
                ('manufactory_code_start', models.PositiveSmallIntegerField(default=0)),
                ('manufactory_code_count', models.PositiveSmallIntegerField(default=0)),
                ('before_fmt', models.CharField(blank=True, default='', max_length=128)),
                ('after_fmt', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'wiegand_count', 'wiegand_name'],
                'indexes': [models.Index(fields=['wiegand_name'], name='agent_wiega_wiegand_116791_idx'), models.Index(fields=['is_active'], name='agent_wiega_is_acti_8989cf_idx'), models.Index(fields=['system_defined'], name='agent_wiega_system__b284da_idx')],
            },
        ),
    ]
