from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="agent-health"),
    path("metrics/", views.metrics, name="agent-metrics"),
    path("metrics/prometheus/", views.prom_metrics, name="agent-metrics-prom"),
    path("monitor/", views.monitor, name="agent-monitor"),
    path("status/", views.status_summary, name="agent-status-summary"),
    path("devices/", views.device_list, name="agent-device-list"),
    path("dashboard/", views.access_dashboard, name="agent-access-dashboard"),
    path("menu/personnel/", views.menu_personnel, name="agent-menu-personnel"),
    path("menu/device/", views.menu_device, name="agent-menu-device"),
    path("menu/access/", views.menu_access_control, name="agent-menu-access"),
    path("access/doors/", views.access_doors, name="agent-access-doors"),
    path("access/time-segments/", views.access_time_segments, name="agent-access-time-segments"),
    path("access/holidays/", views.access_holidays, name="agent-access-holidays"),
    path("access/levels/", views.access_levels, name="agent-access-levels"),
    path("reports/alarms/", views.report_alarm, name="agent-report-alarms"),
    path("reports/events/", views.report_all_events, name="agent-report-events"),
    # CRUD routes
    path("crud/doors/", views.doors_list, name="crud-doors-list"),
    path("crud/doors/new/", views.door_create, name="crud-door-create"),
    path("crud/doors/<int:pk>/edit/", views.door_edit, name="crud-door-edit"),
    path("crud/doors/<int:pk>/delete/", views.door_delete, name="crud-door-delete"),
    path("crud/time-segments/", views.segments_list, name="crud-segments-list"),
    path("crud/time-segments/new/", views.segment_create, name="crud-segment-create"),
    path("crud/time-segments/<int:pk>/edit/", views.segment_edit, name="crud-segment-edit"),
    path("crud/time-segments/<int:pk>/delete/", views.segment_delete, name="crud-segment-delete"),
    path("crud/holidays/", views.holidays_list, name="crud-holidays-list"),
    path("crud/holidays/new/", views.holiday_create, name="crud-holiday-create"),
    path("crud/holidays/<int:pk>/edit/", views.holiday_edit, name="crud-holiday-edit"),
    path("crud/holidays/<int:pk>/delete/", views.holiday_delete, name="crud-holiday-delete"),
    path("crud/access-levels/", views.access_levels_list, name="crud-access-levels-list"),
    path("crud/access-levels/new/", views.access_level_create, name="crud-access-level-create"),
    path("crud/access-levels/<int:pk>/edit/", views.access_level_edit, name="crud-access-level-edit"),
    path("crud/access-levels/<int:pk>/delete/", views.access_level_delete, name="crud-access-level-delete"),
    path("crud/employees/", views.employees_list, name="crud-employees-list"),
    path("crud/employees/json/", views.employees_json_list, name="crud-employees-json"),
    path("crud/employees/new/", views.employee_create, name="crud-employee-create"),
    path("crud/employees/check-personnel-no/", views.check_personnel_no, name="crud-employee-check-personnel"),
    path("crud/employees/check-cards/", views.check_card_numbers, name="crud-employee-check-cards"),
    path("crud/employees/<int:pk>/edit/", views.employee_edit, name="crud-employee-edit"),
    path("crud/employees/<int:pk>/delete/", views.employee_delete, name="crud-employee-delete"),
    path("crud/employees/<int:pk>/inline/", views.employee_inline_update, name="crud-employee-inline"),
    path("crud/employees/import/", views.employee_bulk_import, name="crud-employee-import"),
    path("crud/employees/export/", views.employee_export, name="crud-employee-export"),
    path("crud/doors/<int:pk>/inline/", views.door_inline_update, name="crud-door-inline"),
    # Device extended CRUD
    path("crud/devices/", views.devices_crud_list, name="crud-devices-list"),
    path("crud/devices/new/", views.device_create, name="crud-device-create"),
    path("crud/devices/<int:pk>/edit/", views.device_edit, name="crud-device-edit"),
    path("crud/devices/<int:pk>/delete/", views.device_delete, name="crud-device-delete"),
    path("devices/ping/", views.device_ping, name="device-ping"),
    path("devices/discover/", views.device_discover, name="device-discover"),
    path("devices/port-test/", views.device_port_test, name="device-port-test"),
    # New legacy bridge CRUD routes
    path("crud/depts/", views.depts_list, name="crud-depts-list"),
    path("crud/depts/new/", views.dept_create, name="crud-dept-create"),
    path("crud/depts/<int:pk>/edit/", views.dept_edit, name="crud-dept-edit"),
    path("crud/depts/<int:pk>/update/", views.dept_update_json, name="crud-dept-update"),
    path("crud/depts/<int:pk>/delete/", views.dept_delete, name="crud-dept-delete"),
    path("crud/depts/tree/", views.depts_tree_json, name="crud-depts-tree"),
    path("crud/depts/search/", views.depts_search_json, name="crud-depts-search"),
    path("crud/depts/update-parent/", views.depts_update_parent_json, name="crud-depts-update-parent"),
    path("crud/areas/", views.areas_list, name="crud-areas-list"),
    path("crud/areas/new/", views.area_create, name="crud-area-create"),
    path("crud/areas/<int:pk>/edit/", views.area_edit, name="crud-area-edit"),
    path("crud/areas/<int:pk>/delete/", views.area_delete, name="crud-area-delete"),
    # IssueCards JSON endpoints for modern UI
    path("crud/issuecards/", views.issuecards_json_list, name="crud-issuecards-list"),
    path("crud/issuecards/search/", views.issuecards_json_search, name="crud-issuecards-search"),
    path("crud/issuecards/<str:pk>/detail/", views.issuecard_json_detail, name="crud-issuecard-detail"),
    path("crud/issuecards/new/", views.issuecard_json_create, name="crud-issuecard-create"),
    path("crud/issuecards/<str:pk>/update/", views.issuecard_json_update, name="crud-issuecard-update"),
    # Card read API for hardware integrations
    path("api/cards/read/push/", views.card_read_push, name="api-card-read-push"),
    path("api/cards/read/wait/", views.card_read_wait, name="api-card-read-wait"),
    path("api/listeners/error/", views.listener_error, name="api-listener-error"),
    path("crud/access-logs/", views.access_logs_list, name="crud-access-logs-list"),
    path("logs/view/", views.access_logs_view_module, name="agent-logs-view-module"),
    path("reports/employees/", views.employee_report, name="agent-report-employees"),
    path("events/recent/", views.recent_events_json, name="agent-recent-events"),
    path("api/devices/<int:device_id>/doors/<str:door_id>/open/", views.door_open, name="door-open"),
    path("api/devices/<int:device_id>/doors/<str:door_id>/close/", views.door_close, name="door-close"),
    path("api/devices/<int:device_id>/doors/<str:door_id>/normal-open/", views.door_normal_open, name="door-normal-open"),
    path("api/devices/<int:device_id>/doors/<str:door_id>/cancel-alarm/", views.door_cancel_alarm, name="door-cancel-alarm"),
    path("api/doors/<int:pk>/open/", views.door_pk_open, name="door-pk-open"),
    path("api/doors/<int:pk>/close/", views.door_pk_close, name="door-pk-close"),
    path("api/access/check/", views.access_check, name="access-check"),
    path("api/access/evaluate-open/", views.access_evaluate_and_open, name="access-evaluate-open"),
    path("api/commands/recent/", views.command_recent, name="command-recent"),
    path("shutdown/", views.server_shutdown, name="agent-shutdown"),
    # Control Center (grouped operations & CommCenter management)
    path("control/", views.control_center, name="agent-control-center"),
    path("control/comm-center/status/", views.comm_center_status, name="comm-center-status"),
    path("control/comm-center/start/", views.comm_center_start, name="comm-center-start"),
    path("control/comm-center/stop/", views.comm_center_stop, name="comm-center-stop"),
    path("diagnostics/model-diff/", views.model_diff, name="agent-model-diff"),
    # Readers config/status API
    path("api/readers/config", views.readers_config, name="agent-readers-config"),
    path("api/readers/status", views.readers_status, name="agent-readers-status"),
]
